# Generated by Django 5.1.6 on 2025-03-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eLearningApp", "0002_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
