# Generated by Django 5.1.6 on 2025-03-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eLearningApp", "0006_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocked",
            name="reason",
            field=models.TextField(default="Blocked from course"),
            preserve_default=False,
        ),
    ]
