# Generated by Django 5.1.6 on 2025-03-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eLearningApp", "0007_blocked_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocked",
            name="reason",
            field=models.TextField(verbose_name="Blocked from course."),
        ),
    ]
