# Generated by Django 5.1.6 on 2025-03-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eLearningApp", "0008_alter_blocked_reason"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Enrollment",
            new_name="Enrolment",
        ),
    ]
