# Generated by Django 5.1.6 on 2025-03-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eLearningApp", "0012_alter_blocked_reason_message"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
