# Generated by Django 5.1.6 on 2025-03-08 17:15

import eLearningApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eLearningApp", "0013_delete_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="file",
            field=models.FileField(
                upload_to="course_materials/",
                validators=[eLearningApp.models.validate_file_extension],
            ),
        ),
    ]
