# Generated by Django 5.1.6 on 2025-03-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eLearningApp", "0015_chatmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["created_at"]},
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="timestamp",
            new_name="created_at",
        ),
    ]
